import type { Metadata } from "next";
import "./globals.css";
import '@mantine/core/styles.css';
import { Button, ColorSchemeScript, createTheme, Flex, mantineHtmlProps, MantineProvider, MantineTheme, Text, Title } from "@mantine/core";
import Link from "next/link";

import { Barlow } from 'next/font/google'
import { RootStyleRegistry } from "./EmotionRootStyleRegistry";
import { emotionTransform, MantineEmotionProvider } from "@mantine/emotion";
import { theme } from "../../theme";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" {...mantineHtmlProps} style={{ height: "100%" }}>
      <head>
        <ColorSchemeScript />
      </head>

      <body style={{ height: "100%", overflow: "hidden" }} >


        <MantineProvider theme={theme}      >
          <header>
            <Flex justify="space-between" m="xl" align="center" mb={100}>
              <Title>Cécile LECERF</Title>
              <Flex gap="xl">
                <Link href="#" style={{ textDecoration: "none" }}>
                  <Text fz="h3">Projet</Text>
                </Link>
                <Link href="#">
                  <Text fz="h3">CV</Text>
                </Link>
                <Link href="#">
                  <Text fz="h3">Github</Text>
                </Link>
                <Link href="#">
                  <Text fz="h3">Linkedin</Text>
                </Link>

              </Flex>
            </Flex>
          </header>
          {children}
        </MantineProvider>

      </body >
    </html >
  );
}
