import type { Metadata } from "next";
import "./globals.css";
import '@mantine/core/styles.css';
import { ColorSchemeScript, createTheme, Flex, mantineHtmlProps, MantineProvider, Text, Title } from "@mantine/core";
import Link from "next/link";

import { Barlow } from 'next/font/google'


const barlow = Barlow({
  weight: '400',
  subsets: ['latin'],
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  fontFamily: `${barlow.style.fontFamily}, Verdana, sans-serif`,
  fontFamilyMonospace: 'Monaco, Courier, monospace',
  headings: { fontFamily: `${barlow.style.fontFamily}, Greycliff CF, sans-serif` },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>

      <body  >
        <MantineProvider theme={theme}    >
          <header>
            <Flex justify="space-between" m={54} align="center"  >
              <Title>Cécile LECERF</Title>
              <Flex gap="md">
                <Link href="#" style={{ textDecoration: "none" }}>
                  <Text fz="h3">Projet</Text>
                </Link>
                <Link href="#">
                  <Text fz="h3">CV</Text>
                </Link>
                <Link href="#">
                  <Text fz="h3">Github</Text>
                </Link>
                <Link href="#">
                  <Text fz="h3">Linkedin</Text>
                </Link>

              </Flex>
            </Flex>
          </header>
          {children}
        </MantineProvider>
      </body>
    </html >
  );
}
