import type { Metadata } from 'next';
import './globals.css';
import '@mantine/core/styles.css';
import {
  Box,
  ColorSchemeScript,
  mantineHtmlProps,
  MantineProvider,
} from '@mantine/core';

import { theme } from '../../theme';
import { Header } from '@/components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps} style={{ height: '100%' }}>
      <head>
        <ColorSchemeScript />
      </head>

      <body style={{}}>
        <MantineProvider theme={theme} >
          <Box px={{ base: 20, sm: 100 }}>
            <Header />
            <main>{children}</main>
          </Box>
        </MantineProvider>
      </body>
    </html>
  );
}
